server:
  port: 8081

application:
  security:
    oauth:
      # client1
      client[0]:
        # client id
        client-id: client5
        # client secret
        client-secret: $2a$10$fGSfHZ2ZUrZP6YcdjDsdA.SCd2CvqoQcb50IRA6bmrsv2uHhEnnf6
        # authorization scope
        scope: all
        # access token validity seconds
        access-token-validity-seconds: 6000
        # refresh token validity seconds
        refresh-token-validity-seconds: 6000
        # authorization grant types
        grant-type: authorization_code,password,refresh_token
        # ids allowed to access
        resource-ids: client5
        # redirect uri
        registered-redirect-uri: http://example.com

      # client2
      client[1]:
        client-id: client6
        client-secret: $2a$10$fGSfHZ2ZUrZP6YcdjDsdA.SCd2CvqoQcb50IRA6bmrsv2uHhEnnf6
        scope: all
        access-token-validity-seconds: 6000
        refresh-token-validity-seconds: 6000
        grant-type: authorization_code,password,refresh_token
        resource-ids: client6
        registered-redirect-uri: http://example.com
